### ISSUE TITLE
Using as a view resolver

### ISSUE THREAD

**Issue by codeboulevardsamsudeen** [iceant/rocker-spring-boot-starter#1]
Thank you for a great project
How can I use this project as a view resolver for spring.

**Comment by iceant** [comment]
Thanks for your interesting. I have updated README.md for how to config and use it.
You can check it. Also, you can check com.pointcx.rocker.spring.boot.starter.RockerAutoConfiguration, it will config as the view resolver for you automatically.
I'm applying for release this artifact to maven centrol repository now, hope it could be easy to integration to spring project easily in the future.

**Comment by codeboulevardsamsudeen** [comment]
I have followed the updated README.md and had to add 
    <groupId>com.pointcx</groupId> to the POM.xml but I still get com.fizzed.rocker.TemplateNotFoundException: Compiled template index.rocker.html not found

this is my controller
@RequestMapping(value = "/", method = RequestMethod.GET)
    public void home(){
       return "index";
    }

**Comment by iceant** [comment]
I just created a demo for it. please check this project: 
https://github.com/iceant/demo-rocker-spring-boot-starter
